spring:
  cloud:
    function:
      definition: simpleConsumer
    stream:
      bindings:
        simpleConsumer-in-0:
          destination: demo-topic
          group: demo-group # consumer group
      kafka:
        binder:
          brokers:
            - localhost:8081
          consumer-properties:
            auto.offset.reset: earliest # --from-beginning