spring:
  cloud:
    function:
      definition: orderProcessor
    stream:
      bindings:
        orderProcessor-in-0:
          destination: order-events # producer topic name
          group: order-processor-consumer-group # consumer group
        orderProcessor-out-0:
          destination: digital-delivery-events # topic name
        orderProcessor-out-1:
          destination: physical-delivery-events # topic name
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto.offset.reset: earliest # --from-beginning