spring:
  cloud:
    function:
      definition: orderProducer
    stream:
      bindings:
        orderProducer-out-0:
          destination: order-events # topic name
      poller:
        fixed-delay: 1000 # 1000ms default value
      kafka:
        binder:
          brokers:
            - localhost:9092