spring:
  cloud:
    function:
      definition: messageConsumer
    stream:
      bindings:
        messageConsumer-in-0:
          destination: demo-topic
          group: demo-group  # consumer group
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto.offset.reset: earliest # --from-beginning
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer