spring:
  cloud:
    function:
      definition: physicalOrdersConsumer
    stream:
      bindings:
        physicalOrdersConsumer-in-0:
          destination: physical-delivery-events # topic name
          group: physical-orders-consumer-group
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto.offset.reset: earliest # --from-beginning