spring:
  config:
    import: ${section}/${config}.yaml

# 'section' and 'config' should be provided.
# Example:
# SpringApplication.run(
#     SectionRunner.class,
#     "--section=sec01",
#     "--config=01-simple-consumer"
# );
